### ISSUE TITLE
Compile on 16 bit x86 with terminal output?

### ISSUE THREAD

**Issue by toncho11** [cnlohr/embeddedDOOM#4]
Hi,

Is 32 bits required? There exists a good 16 bit gcc compiler. Would you code compile ?

Maybe this way I could try it on a 8086/8088 using terminal output?

**Comment by toncho11** [comment]
Here is the 16 bit gcc compiler: https://github.com/tkchia/gcc-ia16
It is used to compile ELKS Linux: https://github.com/jbruchon/elks . ELKS has seen a lot of progress in recent years, it is stable and it comes with support for network, fat 16, fat 32, minix fs and some graphics.

**Comment by cnlohr** [comment]
It is really designed to output 32-bit code.  Additionally, the way it works, it needs to be able to "index" into the "flash".

I made my mods mostly to be able to fit this into microcontrollers, where the RODATA is freely accessible.

This is not how 8066/8088 works.  You would still need some mechanism to access extended RAM. 

So, possibly on a 286?

**Comment by toncho11** [comment]
So you had more than 1 MB of RAM on your micro controllers?
ELKS works on 286, 386 and 486, but it will always be 16 bit.
What are the chances in this case?

**Comment by cnlohr** [comment]
In general, you don't need the RAM is the point.  It can be read-only memory, like FLASH.  Though, on x86, that would need to be RAM.

You have a shot. But I don't believe I will try.

**Comment by toncho11** [comment]
Is the code very 32 bit specific? Does many places assume 32 bit word?

**Comment by cnlohr** [comment]
Thinking through it, it would be difficult because it uses more than 16-bits of data for malloc, etc.  I really just don't know very much about the 16-bit era.

**Comment by toncho11** [comment]
Thanks.
