### ISSUE TITLE
additions to the README

### ISSUE THREAD

**Issue by clemdemort** [cnlohr/embeddedDOOM#5]
(this is a suggestion to add this to the readme because I did not want to bother with a pull request)

## dependencies for arch linux:

dependencies :

> sudo pacman -S lib32-libx11 lib32-libxext lib32-libnsl gcc-multilib

then compilation works flawlesly

**Comment by cnlohr** [comment]
If you'd like credit feel free to make a PR.

**Comment by clemdemort** [comment]
Sure thank you!
I came here after seeing your video on RISC-V, you make pretty interesting content :)

**Comment by cnlohr** [comment]
Thanks.
